name: Mini CI

on:
    [push]
jobs:
  test_commit:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Usamos la JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Correr pruebas
          run: mvn verify